import Head from 'next/head'

import styles from '@/styles/Home.module.css'
import {useRef, useState} from "react";

export default function Home() {
    const [position,setPosition] = useState(0)
    const [isMoving,setIsMoving] = useState(false)

    const ref = useRef<any>(null)
    const width = ref.current?.clientWidth

    const onPointerDown = (e:any)=>{
        ref.current.setPointerCapture(e.pointerId)
        setIsMoving(true)
        setPosition(e.clientX/width*100)

    }

    const onPointerMove=(e:any)=>{
        if(!isMoving)return
        setPosition(e.clientX/width*100)
    }
    const onPointerUp=()=>{
        setIsMoving(false)

    }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
            <div className={styles.buttons}>
                <button onClick={()=>setPosition(p=>p+5)}>+</button>
                <button onClick={()=>setPosition(p=>p-5)}>-</button>
            </div>
          <div onPointerUp={()=>onPointerUp()} onPointerMove={(e)=>onPointerMove(e)} ref={ref} onPointerDown={(e)=>onPointerDown(e)} className={styles.timeline}>
              <div style={{
                  left:`${position}%`
              }} className={styles.dot}></div>
              <div style={{
                  width: `${position+3}%`
              }} className={styles.timeline_filled}></div>
          </div>
      </main>
    </>
  )
}
